# Flutter — keep all reflection entry points Flutter relies on.
-keep class io.flutter.** { *; }
-keep class io.flutter.plugins.** { *; }
-dontwarn io.flutter.embedding.**

# Drift / SQLite — generated DAO classes use reflection.
-keep class androidx.sqlite.** { *; }
-keep class app.cash.sqldelight.** { *; }
-dontwarn app.cash.sqldelight.**

# Dart-mapped classes (generated by drift_dev) must not be renamed.
-keep class * extends drift.** { *; }
-keepclassmembers class * {
    @drift.** *;
}

# just_audio — ExoPlayer internals.
-keep class com.google.android.exoplayer2.** { *; }
-dontwarn com.google.android.exoplayer2.**

# Dio / OkHttp — HTTP client reflection.
-dontwarn okhttp3.**
-dontwarn okio.**
-keep class okhttp3.** { *; }
-keep interface okhttp3.** { *; }

# share_plus — native share sheet.
-keep class dev.fluttercommunity.plus.share.** { *; }

# flutter_tts — keep TTS engine classes.
-keep class com.tundralabs.fluttertts.** { *; }

# Kotlin coroutines.
-keepnames class kotlinx.coroutines.internal.MainDispatcherFactory {}
-keepnames class kotlinx.coroutines.CoroutineExceptionHandler {}
-keepclassmembernames class kotlinx.** {
    volatile <fields>;
}
